
// Action Types

export const GET_ALLTODOS_REQUEST = "GET_ALLTODOS_REQUEST";
export const GET_ALLTODOS_SUCCESS = "GET_ALLTODOS_SUCCESS";
export const GET_ALLTODOS_FAIL = "GET_ALLTODOS_FAIL";

export const TODO_ADD_REQUEST = "TODO_ADD_REQUEST";
export const TODO_ADD_SUCCESS = "TODO_ADD_SUCCESS";
export const TODO_ADD_FAIL = "TODO_ADD_FAIL";

export const TODO_DELETE_REQUEST = "TODO_DELETE_REQUEST";
export const TODO_DELETE_SUCCESS = "TODO_DELETE_SUCCESS";
export const TODO_DELETE_FAIL = "TODO_DELETE_FAIL";


export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";